extends: bases/cmake-ninja.yaml

name: llvm-project
description: LLVM core and Clang

repository:
  url: https://github.com/llvm/llvm-project.git
  directory: llvm-project
  depth: 1

variables:
  source_dir: llvm
  build_dir: build-scip
  cmake_args: >-
    -DCMAKE_BUILD_TYPE=Release
    -DLLVM_ENABLE_PROJECTS=clang
    -DLLVM_TARGETS_TO_BUILD=Native
    -DLLVM_ENABLE_ASSERTIONS=OFF
