name: expat
repoUrl: https://github.com/libexpat/libexpat.git
build: |
  SOURCE_DIR="$SOURCE_DIR/expat" exec .github/scripts/build-cmake-project.sh \
    -DEXPAT_BUILD_TESTS=OFF \
    -DEXPAT_BUILD_EXAMPLES=OFF \
    -DEXPAT_BUILD_TOOLS=OFF \
    -DEXPAT_SHARED_LIBS=OFF
