name: nginx
repoUrl: https://github.com/nginx/nginx.git
ccacheMaxSize: 50M
build: |
  cd "$SOURCE_DIR"
  ./auto/configure --with-cc="ccache clang" --with-cc-opt=-O2
  bear --output "$BUILD_DIR/compile_commands.json" -- make -j"$BUILD_JOBS"
