name: sqlite
repoUrl: https://github.com/sqlite/sqlite.git
build: |
  cd "$SOURCE_DIR"
  CC="ccache clang" ./configure --disable-shared --disable-readline
  bear --output "$BUILD_DIR/compile_commands.json" -- make -j"$BUILD_JOBS"
