name: zstd
repoUrl: https://github.com/facebook/zstd.git
build: |
  SOURCE_DIR="$SOURCE_DIR/build/cmake" exec .github/scripts/build-cmake-project.sh \
    -DZSTD_BUILD_PROGRAMS=OFF \
    -DZSTD_BUILD_TESTS=OFF \
    -DZSTD_BUILD_SHARED=OFF \
    -DZSTD_BUILD_STATIC=ON
